type FilterCategory = {
  title: string,
  value?: string
}

const materials: FilterCategory[] = [
  {title: "Aagte"}, 
  {title: "Amulets"}, 
  {title: "Aquatint"}, 
  {title: "Arms"}, 
  {title: "Beads"}, 
  {title: "Bone"}, 
  {title: "Books"}, 
  {title: "Bottles"}, 
  {title: "Bowls"}, 
  {title: "Bows"}, 
  {title: "Bronze"}, 
  {title: "Canvas"}, 
  {title: "Ceramics"}, 
  {title: "Chalcedony"}, 
  {title: "Chordophones"}, 
  {title: "Clay"}, 
  {title: "Color lithographs"}, 
  {title: "Copper"}, 
  {title: "Copper alloy"}, 
  {title: "Costume"}, 
  {title: "Dishes"}, 
  {title: "Drawings"}, 
  {title: "Drums"}, 
  {title: "Earthenware"}, 
  {title: "Ebony"}, 
  {title: "Edged weapons"}, 
  {title: "Engraving"}, 
  {title: "Ephemera"}, 
  {title: "Etching"}, 
  {title: "Faience"}, 
  {title: "Figures"}, 
  {title: "Figurines"}, 
  {title: "Frogs"}, 
  {title: "Furniture"}, 
  {title: "Gilt"}, 
  {title: "Glass"}, 
  {title: "Glaze"}, 
  {title: "Glazing"}, 
  {title: "Gold"}, 
  {title: "Gold alloy"}, 
  {title: "Graphite"}, 
  {title: "Hair"}, 
  {title: "Hanging scrolls"}, 
  {title: "Horsehair"}, 
  {title: "Idiophones"}, 
  {title: "Ink"}, 
  {title: "Iron"}, 
  {title: "Iron alloy"}, 
  {title: "Iron and iron alloy"}, 
  {title: "Ivory"}, 
  {title: "Jade"}, 
  {title: "Jars"}, 
  {title: "Jewelry"}, 
  {title: "Knives"}, 
  {title: "Lacquer"}, 
  {title: "Lapis lazuli"}, 
  {title: "Leather"}, 
  {title: "Limestone"}, 
  {title: "Lithographs"}, 
  {title: "Membranophones"}, 
  {title: "Metal"}, 
  {title: "Metalwork"}, 
  {title: "Molds"}, 
  {title: "Musical instruments"}, 
  {title: "Netsukes"}, 
  {title: "Paintings"}, 
  {title: "Paper"}, 
  {title: "Pendants"}, 
  {title: "Photograms"}, 
  {title: "Photographs"}, 
  {title: "Photogravures"}, 
  {title: "Photomechanical reproductions"}, 
  {title: "Planographic prints"}, 
  {title: "Porcelain"}, 
  {title: "Pottery"}, 
  {title: "Printing blocks"}, 
  {title: "Prints"}, 
  {title: "Relief prints"}, 
  {title: "Scroll paintings"}, 
  {title: "Scrolls"}, 
  {title: "Sculpture"}, 
  {title: "Seals"}, 
  {title: "Silk"}, 
  {title: "Silver"}, 
  {title: "Silver alloy"}, 
  {title: "Silver-dye bleach prints"}, 
  {title: "Snuff bottles"}, 
  {title: "Snuff containers"}, 
  {title: "Stamps"}, 
  {title: "Statues"}, 
  {title: "Stone"}, 
  {title: "Swords"}, 
  {title: "Vases"}, 
  {title: "Vessels"}, 
  {title: "Violins"}, 
  {title: "Watercolors"}, 
  {title: "Wood"}, 
  {title: "Wood blocks"}, 
  {title: "Wood engravings"},
  {title: "Woodcuts"}
]

const regions: FilterCategory[] = [
  {title: "Abydos"},
  {title: "Africa"},
  {title: "Al Lisht"},
  {title: "Amarna"},
  {title: "Anatolia"},
  {title: "Angers"},
  {title: "Antwerp"},
  {title: "Asia"},
  {title: "Augsburg"},
  {title: "Austria"},
  {title: "Baden-Württemberg"},
  {title: "Bavaria"},
  {title: "Beaune"},
  {title: "Belgium"},
  {title: "Bennington"},
  {title: "Birmingham"},
  {title: "Bohemia"},
  {title: "Brooklyn"},
  {title: "Burgundy"},
  {title: "Cambodia"},
  {title: "Canada"},
  {title: "Chelsea"},
  {title: "China"},
  {title: "Colima"},
  {title: "Colombia"},
  {title: "Costa Rica"},
  {title: "Cyprus"},
  {title: "Czech Republic"},
  {title: "Denmark"},
  {title: "Egypt"},
  {title: "England"},
  {title: "Europe"},
  {title: "Flanders"},
  {title: "Florence"},
  {title: "France"},
  {title: "Frankfurt-am-Main"},
  {title: "Germany"},
  {title: "Ghana"},
  {title: "Greece"},
  {title: "Guerrero"},
  {title: "Hesse"},
  {title: "Indonesia"},
  {title: "Innsbruck"},
  {title: "Iran"},
  {title: "Iraq"},
  {title: "Irian Jaya"},
  {title: "Italy"},
  {title: "Japan"},
  {title: "Java"},
  {title: "Korea"},
  {title: "Laconia"},
  {title: "Lao"},
  {title: "Leipzig"},
  {title: "London"},
  {title: "Luristan"},
  {title: "Markneukirchen"},
  {title: "Massachusetts"},
  {title: "Meissen"},
  {title: "Mersa Matrûh"},
  {title: "Mexico"},
  {title: "Missouri"},
  {title: "Moscow"},
  {title: "Netherlands"},
  {title: "New Mexico"},
  {title: "New York"},
  {title: "New York City"},
  {title: "North and Central America"},
  {title: "Ohio"},
  {title: "Padua"},
  {title: "Panama"},
  {title: "Paris"},
  {title: "Peloponnese"},
  {title: "Pennsylvania"},
  {title: "Peru"},
  {title: "Philadelphia"},
  {title: "Roman Empire"},
  {title: "Rome"},
  {title: "Russia"},
  {title: "Saint Petersburg"},
  {title: "Saint-Amand-en-Puisaye"},
  {title: "Saqqara"},
  {title: "Saxony"},
  {title: "South America"},
  {title: "Southwest"},
  {title: "Staffordshire"},
  {title: "Stuttgart"},
  {title: "Switzerland"},
  {title: "Thailand"},
  {title: "Thebes"},
  {title: "Turkey"},
  {title: "Tuscany"},
  {title: "Tyrol"},
  {title: "United Kingdom"},
  {title: "United States"},
  {title: "Upper Egypt"},
  {title: "Urbania"},
  {title: "Veracruz"},
  {title: "Vermont"},
  {title: "Vietnam"},
  {title: "West Midlands"}
]

const dates: FilterCategory[] = [
  {title: "A.D. 1800-1900"},
  {title: "A.D. 1900-present"},
  {title: "A.D. 1600-1800"},
  {title: "2000-1000 B.C."},
  {title: "1000 B.C.-A.D. 1"},
  {title: "A.D. 1400-1600"},
  {title: "8000-2000 B.C."},
  {title: "A.D. 500-1000"},
  {title: "A.D. 1-500"},
  {title: "A.D. 1000-1400"}
]

const departments: FilterCategory[] = [
  {title: "The American Wing"}, 
  {title: "Ancient Near Eastern Art"}, 
  {title: "Arms and Armor"}, 
  {title: "Asian Art"}, 
  {title: "Brooklyn Museum Costume Collection"}, 
  {title: "The Cloisters"}, 
  {title: "Costume Institute"}, 
  {title: "Drawings and Prints"}, 
  {title: "Egyptian Art"}, 
  {title: "European Paintings"}, 
  {title: "European Sculpture and Decorative Arts"}, 
  {title: "Greek and Roman Art"}, 
  {title: "Medieval Art"}, 
  {title: "The Michael C. Rockefeller Wing"}, 
  {title: "Modern and Contemporary Art"}, 
  {title: "Musical Instruments"}, 
  {title: "Photographs"}, 
  {title: "Robert Lehman Collection"}
]

export const checkboxFilters: FilterCategory[] = [
  {title: "Highlights"},
  {title: "Artworks With Image"},
  {title: "Artworks on Display"},
]

export const filters: {[key: string]: FilterCategory[]} = {
  'Object Type / Materials': materials,
  'Geographic Location': regions,
  'Date / Era': dates,
  'Department': departments,
}

