export type FilterCategory = {
  title: string,
  category: string,
}

const materials: FilterCategory[] = [
  {title: "Aagte", category: 'Object Type / Materials'}, 
  {title: "Amulets", category: 'Object Type / Materials'}, 
  {title: "Aquatint", category: 'Object Type / Materials'}, 
  {title: "Arms", category: 'Object Type / Materials'}, 
  {title: "Beads", category: 'Object Type / Materials'}, 
  {title: "Bone", category: 'Object Type / Materials'}, 
  {title: "Books", category: 'Object Type / Materials'}, 
  {title: "Bottles", category: 'Object Type / Materials'}, 
  {title: "Bowls", category: 'Object Type / Materials'}, 
  {title: "Bows", category: 'Object Type / Materials'}, 
  {title: "Bronze", category: 'Object Type / Materials'}, 
  {title: "Canvas", category: 'Object Type / Materials'}, 
  {title: "Ceramics", category: 'Object Type / Materials'}, 
  {title: "Chalcedony", category: 'Object Type / Materials'}, 
  {title: "Chordophones", category: 'Object Type / Materials'}, 
  {title: "Clay", category: 'Object Type / Materials'}, 
  {title: "Color lithographs", category: 'Object Type / Materials'}, 
  {title: "Copper", category: 'Object Type / Materials'}, 
  {title: "Copper alloy", category: 'Object Type / Materials'}, 
  {title: "Costume", category: 'Object Type / Materials'}, 
  {title: "Dishes", category: 'Object Type / Materials'}, 
  {title: "Drawings", category: 'Object Type / Materials'}, 
  {title: "Drums", category: 'Object Type / Materials'}, 
  {title: "Earthenware", category: 'Object Type / Materials'}, 
  {title: "Ebony", category: 'Object Type / Materials'}, 
  {title: "Edged weapons", category: 'Object Type / Materials'}, 
  {title: "Engraving", category: 'Object Type / Materials'}, 
  {title: "Ephemera", category: 'Object Type / Materials'}, 
  {title: "Etching", category: 'Object Type / Materials'}, 
  {title: "Faience", category: 'Object Type / Materials'}, 
  {title: "Figures", category: 'Object Type / Materials'}, 
  {title: "Figurines", category: 'Object Type / Materials'}, 
  {title: "Frogs", category: 'Object Type / Materials'}, 
  {title: "Furniture", category: 'Object Type / Materials'}, 
  {title: "Gilt", category: 'Object Type / Materials'}, 
  {title: "Glass", category: 'Object Type / Materials'}, 
  {title: "Glaze", category: 'Object Type / Materials'}, 
  {title: "Glazing", category: 'Object Type / Materials'}, 
  {title: "Gold", category: 'Object Type / Materials'}, 
  {title: "Gold alloy", category: 'Object Type / Materials'}, 
  {title: "Graphite", category: 'Object Type / Materials'}, 
  {title: "Hair", category: 'Object Type / Materials'}, 
  {title: "Hanging scrolls", category: 'Object Type / Materials'}, 
  {title: "Horsehair", category: 'Object Type / Materials'}, 
  {title: "Idiophones", category: 'Object Type / Materials'}, 
  {title: "Ink", category: 'Object Type / Materials'}, 
  {title: "Iron", category: 'Object Type / Materials'}, 
  {title: "Iron alloy", category: 'Object Type / Materials'}, 
  {title: "Iron and iron alloy", category: 'Object Type / Materials'}, 
  {title: "Ivory", category: 'Object Type / Materials'}, 
  {title: "Jade", category: 'Object Type / Materials'}, 
  {title: "Jars", category: 'Object Type / Materials'}, 
  {title: "Jewelry", category: 'Object Type / Materials'}, 
  {title: "Knives", category: 'Object Type / Materials'}, 
  {title: "Lacquer", category: 'Object Type / Materials'}, 
  {title: "Lapis lazuli", category: 'Object Type / Materials'}, 
  {title: "Leather", category: 'Object Type / Materials'}, 
  {title: "Limestone", category: 'Object Type / Materials'}, 
  {title: "Lithographs", category: 'Object Type / Materials'}, 
  {title: "Membranophones", category: 'Object Type / Materials'}, 
  {title: "Metal", category: 'Object Type / Materials'}, 
  {title: "Metalwork", category: 'Object Type / Materials'}, 
  {title: "Molds", category: 'Object Type / Materials'}, 
  {title: "Musical instruments", category: 'Object Type / Materials'}, 
  {title: "Netsukes", category: 'Object Type / Materials'}, 
  {title: "Paintings", category: 'Object Type / Materials'}, 
  {title: "Paper", category: 'Object Type / Materials'}, 
  {title: "Pendants", category: 'Object Type / Materials'}, 
  {title: "Photograms", category: 'Object Type / Materials'}, 
  {title: "Photographs", category: 'Object Type / Materials'}, 
  {title: "Photogravures", category: 'Object Type / Materials'}, 
  {title: "Photomechanical reproductions", category: 'Object Type / Materials'}, 
  {title: "Planographic prints", category: 'Object Type / Materials'}, 
  {title: "Porcelain", category: 'Object Type / Materials'}, 
  {title: "Pottery", category: 'Object Type / Materials'}, 
  {title: "Printing blocks", category: 'Object Type / Materials'}, 
  {title: "Prints", category: 'Object Type / Materials'}, 
  {title: "Relief prints", category: 'Object Type / Materials'}, 
  {title: "Scroll paintings", category: 'Object Type / Materials'}, 
  {title: "Scrolls", category: 'Object Type / Materials'}, 
  {title: "Sculpture", category: 'Object Type / Materials'}, 
  {title: "Seals", category: 'Object Type / Materials'}, 
  {title: "Silk", category: 'Object Type / Materials'}, 
  {title: "Silver", category: 'Object Type / Materials'}, 
  {title: "Silver alloy", category: 'Object Type / Materials'}, 
  {title: "Silver-dye bleach prints", category: 'Object Type / Materials'}, 
  {title: "Snuff bottles", category: 'Object Type / Materials'}, 
  {title: "Snuff containers", category: 'Object Type / Materials'}, 
  {title: "Stamps", category: 'Object Type / Materials'}, 
  {title: "Statues", category: 'Object Type / Materials'}, 
  {title: "Stone", category: 'Object Type / Materials'}, 
  {title: "Swords", category: 'Object Type / Materials'}, 
  {title: "Vases", category: 'Object Type / Materials'}, 
  {title: "Vessels", category: 'Object Type / Materials'}, 
  {title: "Violins", category: 'Object Type / Materials'}, 
  {title: "Watercolors", category: 'Object Type / Materials'}, 
  {title: "Wood", category: 'Object Type / Materials'}, 
  {title: "Wood blocks", category: 'Object Type / Materials'}, 
  {title: "Wood engravings", category: 'Object Type / Materials'},
  {title: "Woodcuts", category: 'Object Type / Materials'}
]

const regions: FilterCategory[] = [
  {title: "Abydos", category: 'Geographic Location'},
  {title: "Africa", category: 'Geographic Location'},
  {title: "Al Lisht", category: 'Geographic Location'},
  {title: "Amarna", category: 'Geographic Location'},
  {title: "Anatolia", category: 'Geographic Location'},
  {title: "Angers", category: 'Geographic Location'},
  {title: "Antwerp", category: 'Geographic Location'},
  {title: "Asia", category: 'Geographic Location'},
  {title: "Augsburg", category: 'Geographic Location'},
  {title: "Austria", category: 'Geographic Location'},
  {title: "Baden-Württemberg", category: 'Geographic Location'},
  {title: "Bavaria", category: 'Geographic Location'},
  {title: "Beaune", category: 'Geographic Location'},
  {title: "Belgium", category: 'Geographic Location'},
  {title: "Bennington", category: 'Geographic Location'},
  {title: "Birmingham", category: 'Geographic Location'},
  {title: "Bohemia", category: 'Geographic Location'},
  {title: "Brooklyn", category: 'Geographic Location'},
  {title: "Burgundy", category: 'Geographic Location'},
  {title: "Cambodia", category: 'Geographic Location'},
  {title: "Canada", category: 'Geographic Location'},
  {title: "Chelsea", category: 'Geographic Location'},
  {title: "China", category: 'Geographic Location'},
  {title: "Colima", category: 'Geographic Location'},
  {title: "Colombia", category: 'Geographic Location'},
  {title: "Costa Rica", category: 'Geographic Location'},
  {title: "Cyprus", category: 'Geographic Location'},
  {title: "Czech Republic", category: 'Geographic Location'},
  {title: "Denmark", category: 'Geographic Location'},
  {title: "Egypt", category: 'Geographic Location'},
  {title: "England", category: 'Geographic Location'},
  {title: "Europe", category: 'Geographic Location'},
  {title: "Flanders", category: 'Geographic Location'},
  {title: "Florence", category: 'Geographic Location'},
  {title: "France", category: 'Geographic Location'},
  {title: "Frankfurt-am-Main", category: 'Geographic Location'},
  {title: "Germany", category: 'Geographic Location'},
  {title: "Ghana", category: 'Geographic Location'},
  {title: "Greece", category: 'Geographic Location'},
  {title: "Guerrero", category: 'Geographic Location'},
  {title: "Hesse", category: 'Geographic Location'},
  {title: "Indonesia", category: 'Geographic Location'},
  {title: "Innsbruck", category: 'Geographic Location'},
  {title: "Iran", category: 'Geographic Location'},
  {title: "Iraq", category: 'Geographic Location'},
  {title: "Irian Jaya", category: 'Geographic Location'},
  {title: "Italy", category: 'Geographic Location'},
  {title: "Japan", category: 'Geographic Location'},
  {title: "Java", category: 'Geographic Location'},
  {title: "Korea", category: 'Geographic Location'},
  {title: "Laconia", category: 'Geographic Location'},
  {title: "Lao", category: 'Geographic Location'},
  {title: "Leipzig", category: 'Geographic Location'},
  {title: "London", category: 'Geographic Location'},
  {title: "Luristan", category: 'Geographic Location'},
  {title: "Markneukirchen", category: 'Geographic Location'},
  {title: "Massachusetts", category: 'Geographic Location'},
  {title: "Meissen", category: 'Geographic Location'},
  {title: "Mersa Matrûh", category: 'Geographic Location'},
  {title: "Mexico", category: 'Geographic Location'},
  {title: "Missouri", category: 'Geographic Location'},
  {title: "Moscow", category: 'Geographic Location'},
  {title: "Netherlands", category: 'Geographic Location'},
  {title: "New Mexico", category: 'Geographic Location'},
  {title: "New York", category: 'Geographic Location'},
  {title: "New York City", category: 'Geographic Location'},
  {title: "North and Central America", category: 'Geographic Location'},
  {title: "Ohio", category: 'Geographic Location'},
  {title: "Padua", category: 'Geographic Location'},
  {title: "Panama", category: 'Geographic Location'},
  {title: "Paris", category: 'Geographic Location'},
  {title: "Peloponnese", category: 'Geographic Location'},
  {title: "Pennsylvania", category: 'Geographic Location'},
  {title: "Peru", category: 'Geographic Location'},
  {title: "Philadelphia", category: 'Geographic Location'},
  {title: "Roman Empire", category: 'Geographic Location'},
  {title: "Rome", category: 'Geographic Location'},
  {title: "Russia", category: 'Geographic Location'},
  {title: "Saint Petersburg", category: 'Geographic Location'},
  {title: "Saint-Amand-en-Puisaye", category: 'Geographic Location'},
  {title: "Saqqara", category: 'Geographic Location'},
  {title: "Saxony", category: 'Geographic Location'},
  {title: "South America", category: 'Geographic Location'},
  {title: "Southwest", category: 'Geographic Location'},
  {title: "Staffordshire", category: 'Geographic Location'},
  {title: "Stuttgart", category: 'Geographic Location'},
  {title: "Switzerland", category: 'Geographic Location'},
  {title: "Thailand", category: 'Geographic Location'},
  {title: "Thebes", category: 'Geographic Location'},
  {title: "Turkey", category: 'Geographic Location'},
  {title: "Tuscany", category: 'Geographic Location'},
  {title: "Tyrol", category: 'Geographic Location'},
  {title: "United Kingdom", category: 'Geographic Location'},
  {title: "United States", category: 'Geographic Location'},
  {title: "Upper Egypt", category: 'Geographic Location'},
  {title: "Urbania", category: 'Geographic Location'},
  {title: "Veracruz", category: 'Geographic Location'},
  {title: "Vermont", category: 'Geographic Location'},
  {title: "Vietnam", category: 'Geographic Location'},
  {title: "West Midlands", category: 'Geographic Location'}
]

const dates: FilterCategory[] = [
  {title: "A.D. 1800-1900", category: 'Date / Era'},
  {title: "A.D. 1900-present", category: 'Date / Era'},
  {title: "A.D. 1600-1800", category: 'Date / Era'},
  {title: "2000-1000 B.C.", category: 'Date / Era'},
  {title: "1000 B.C.-A.D. 1", category: 'Date / Era'},
  {title: "A.D. 1400-1600", category: 'Date / Era'},
  {title: "8000-2000 B.C.", category: 'Date / Era'},
  {title: "A.D. 500-1000", category: 'Date / Era'},
  {title: "A.D. 1-500", category: 'Date / Era'},
  {title: "A.D. 1000-1400", category: 'Date / Era'}
]

const departments: FilterCategory[] = [
  {title: "The American Wing", category: 'Department'}, 
  {title: "Ancient Near Eastern Art", category: 'Department'}, 
  {title: "Arms and Armor", category: 'Department'}, 
  {title: "Asian Art", category: 'Department'}, 
  {title: "Brooklyn Museum Costume Collection", category: 'Department'}, 
  {title: "The Cloisters", category: 'Department'}, 
  {title: "Costume Institute", category: 'Department'}, 
  {title: "Drawings and Prints", category: 'Department'}, 
  {title: "Egyptian Art", category: 'Department'}, 
  {title: "European Paintings", category: 'Department'}, 
  {title: "European Sculpture and Decorative Arts", category: 'Department'}, 
  {title: "Greek and Roman Art", category: 'Department'}, 
  {title: "Medieval Art", category: 'Department'}, 
  {title: "The Michael C. Rockefeller Wing", category: 'Department'}, 
  {title: "Modern and Contemporary Art", category: 'Department'}, 
  {title: "Musical Instruments", category: 'Department'}, 
  {title: "Photographs", category: 'Department'}, 
  {title: "Robert Lehman Collection", category: 'Department'}
]

export const checkboxFilters: FilterCategory[] = [
  {title: "Highlights", category: 'checkboxes'},
  {title: "Artworks With Image", category: 'checkboxes'},
  {title: "Artworks on Display", category: 'checkboxes'},
]

export const filters: {[key: string]: FilterCategory[]} = {
  'Object Type / Materials': materials,
  'Geographic Location': regions,
  'Date / Era': dates,
  'Department': departments,
}

